/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eb7e85e4-ab24-496c-803b-632dfcf6f074",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_r4bmhU2PX",
    "aws_user_pools_web_client_id": "3i3ddcc5afoeq0lkv0c94fn8an",
    "oauth": {}
};


export default awsmobile;
